![](https://www.saturdays.ai/images/logo.png)

# SF Salaries Exercise

Welcome to a quick exercise for you to practice your pandas skills! We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

** Import pandas as pd.**

In [ ]:
import pandas as pd

** Read Salaries.csv as a dataframe called sal.**

In [ ]:
import kagglehub
import os

path = kagglehub.dataset_download("kaggle/sf-salaries")

print("Path to dataset files:", path)
df = pd.read_csv(os.path.join(path, "Salaries.csv"))

Using Colab cache for faster access to the 'sf-salaries' dataset.
Path to dataset files: /kaggle/input/sf-salaries

/tmp/ipython-input-2124303694.py:7: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(path, "Salaries.csv"))

** Check the head of the DataFrame. **

In [ ]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

** Use the .info() method to find out how many entries there are.**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

**What is the average BasePay ?**

In [ ]:
df["BasePay"].unique()

array([167411.18, 155966.02, 212739.13, ..., '6.04', '15.50',
       'Not Provided'], dtype=object)

In [ ]:
df["BasePay_float"] = pd.to_numeric(df["BasePay"], errors="coerce") # coerce pasa a nan los errores
print(df["BasePay_float"].mean())

66325.4488404877

66325.44884050643

** What is the highest amount of OvertimePay in the dataset ? **

In [ ]:
df["OvertimePay"].unique()
overtime_pay_num = pd.to_numeric(df["OvertimePay"], errors ="coerce")
print(overtime_pay_num.max())

#print(pd.to_numeric(df["OvertimePay"], errors ="coerce").max())

245131.88

245131.88

** What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll). **

In [ ]:
df.head()
df['EmployeeName'] == 'JOSEPH DRISCOLL'
df[df['EmployeeName'] == 'JOSEPH DRISCOLL']
df[df['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

** How much does JOSEPH DRISCOLL make (including benefits)? **

In [ ]:
df['EmployeeName'] == 'JOSEPH DRISCOLL'
df[df['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

24    270324.91
Name: TotalPayBenefits, dtype: float64

** What is the name of highest paid person (including benefits)?**

In [ ]:
df.loc[[df['TotalPayBenefits'].idxmax()]]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status,BasePay_float
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN,167411.18

** What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [ ]:
df.loc[[df['TotalPayBenefits'].idxmin()]]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status,BasePay_float
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT,0.0

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

** What was the average (mean) BasePay of all employees per year? (2011-2014) ? **

In [ ]:
df['BasePay'].unique()
df['BasePay_float'] = pd.to_numeric(df['BasePay'], errors="coerce")
df.groupby('Year')['BasePay_float'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay_float, dtype: float64

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

** How many unique job titles are there? **

In [ ]:
df['JobTitle'].nunique()

2159

2159

** What are the top 5 most common jobs? **

In [ ]:
df['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

** How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?) **

Mi nota: filter() no acepta una serie booleana directamente.

In [ ]:
df.head()
df_year_2013 = df[df['Year'] == 2013]
jobemployee_count = df_year_2013.groupby('JobTitle')['EmployeeName'].count()
#type(jobemployee_count)
#print(jobemployee_count)
count_one = jobemployee_count[jobemployee_count == 1]
print(count_one.count())

202

In [ ]:
202

202

** How many people have the word Chief in their job title? (This is pretty tricky) **

In [ ]:
chief = df['JobTitle'].str.contains(r'\bChief\b').sum()
print(chief)

423

477

** Bonus: Is there a correlation between length of the Job Title string and Salary? **

La pregunta es: **¿los puestos con nombres más largos tienden a tener salarios más altos?**

In [ ]:
# Valor de correlacion
df['JobTitle_len'] = df['JobTitle'].str.len()
df.head(3)
print(df['JobTitle_len'].corr(df['TotalPayBenefits']))

-0.036878445932606675

In [ ]:
# Una matriz de correlación
df_corr = df[['JobTitle_len','TotalPayBenefits']]
df_corr.corr()

                  JobTitle_len  TotalPayBenefits
JobTitle_len          1.000000         -0.036878
TotalPayBenefits     -0.036878          1.000000

In [ ]:
# Forma con apply
df['JobTitle_len'] = df['JobTitle'].apply(lambda x: len(x))
df[['JobTitle_len','TotalPayBenefits']].corr()

                  JobTitle_len  TotalPayBenefits
JobTitle_len          1.000000         -0.036878
TotalPayBenefits     -0.036878          1.000000

                  title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000

# Great Job!